# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import action as evt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(452, 674)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(452, 674))
        MainWindow.setMaximumSize(QtCore.QSize(452, 674))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.encrypt = QtWidgets.QWidget()
        self.encrypt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.encrypt.setObjectName("encrypt")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.encrypt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.imgView = QtWidgets.QLabel(self.encrypt)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.imgView.sizePolicy().hasHeightForWidth())
        self.imgView.setSizePolicy(sizePolicy)
        self.imgView.setMinimumSize(QtCore.QSize(300, 500))
        self.imgView.setBaseSize(QtCore.QSize(0, 0))
        self.imgView.setStyleSheet("background-color: rgba(0, 0, 0, 90);")
        self.imgView.setText("")
        self.imgView.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView.setObjectName("imgView")
        self.verticalLayout_2.addWidget(
            self.imgView, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Tombol encrypt
        self.encImg = QtWidgets.QPushButton(self.encrypt)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.encImg.sizePolicy().hasHeightForWidth())
        self.encImg.setSizePolicy(sizePolicy)
        self.encImg.setMinimumSize(QtCore.QSize(200, 0))
        self.encImg.setObjectName("encImg")
        self.encImg.setEnabled(False)
        self.encImg.clicked.connect(lambda: evt.encImgOnClick(self))
        self.horizontalLayout.addWidget(self.encImg)

        # Tombol decrypt
        self.decImg = QtWidgets.QPushButton(self.encrypt)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.decImg.sizePolicy().hasHeightForWidth())
        self.decImg.setSizePolicy(sizePolicy)
        self.decImg.setMinimumSize(QtCore.QSize(200, 0))
        self.decImg.setObjectName("decImg")
        self.decImg.setEnabled(False)
        self.horizontalLayout.addWidget(self.decImg)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # Tombol pilih gambar
        self.selectImg = QtWidgets.QPushButton(self.encrypt)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.selectImg.sizePolicy().hasHeightForWidth())
        self.selectImg.setSizePolicy(sizePolicy)
        self.selectImg.setMinimumSize(QtCore.QSize(200, 0))
        self.selectImg.clicked.connect(lambda: evt.selectImgOnClick(self))
        self.selectImg.setObjectName("selectImg")
        self.verticalLayout.addWidget(
            self.selectImg, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.encrypt, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "DES Image Encryption"))
        self.encImg.setText(_translate("MainWindow", "Encrypt"))
        self.decImg.setText(_translate("MainWindow", "Decrypt"))
        self.selectImg.setText(_translate("MainWindow", "Select Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.encrypt), _translate("MainWindow", "Encrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
